version: "3.9"
services:
  frontend:
    build: ./SFASUI
    expose:
      - 3000
    env_file:
      - .env
  backend:
    build: ../sportsmap-api
    expose:
      - ${API_PORT}
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
