version: "3.9"
services:
  frontend:
    build: ./SFASUI
    expose:
      - 3000
  backend:
    build: ./SFASServer
    expose:
      - 6002
      - 6001
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend