version: "3.9"
services:
  front:
    image: "cr.yandex/${REGISTRY_ID}/sportsmap:latest"
    ports:
      - "3000:3000"
    env_file:
      - local.env
  back:
    image: "cr.yandex/${REGISTRY_ID}/sportsmap-backend:latest"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - local.env
networks:
  default:
    driver: host