name: autotests

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10
        uses: actions/setup-node@v3
        with:
          node-version: 16.10
      - run: yarn install
        working-directory: ./SFASUI
      - run: yarn build
        working-directory: ./SFASUI
      - run: yarn test:jest
        working-directory: ./SFASUI