name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-docker-version
        run: sh ./SFASUI/scripts/get-version.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          IMAGE_NAME: sportsmap

      - name: deploy-docker-frontend
        run: sh ./SFASUI/scripts/deploy.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          VERSION: ${{ env.NEW_VERSION }}