name: storybook

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        working-directory: SFASUI
      - uses: chromaui/action@v1
        with:
          workingDir: SFASUI
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
